server:
  port: 9999

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: cvservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/resume
        - id: cvservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/resume/**
        - id: cvservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/candidates
        - id: cvservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/candidates/**
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/login
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/register
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/logout
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/refreshtoken
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user
        - id: userservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
