server:
  port: 5001

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  applications:
    name: user-service

  data:
    mongodb:
      #authentication-database: admin
      host: localhost
      database: database_cv
      port: 27017
      #username: root
      #password: root

jwt:
  accessTokenSecret: _@tos2022
  refreshTokenSecret: _!-@tos2022
  accessTokenExpirationMinutes: 5
  refreshTokenExpirationDays: 30

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/register-service

